redis = "12800"

[train]
resume = "None"
epoch = 1
output_dir = "./outputs/deepseek-vlm-test"
epsilon = 1e-6
optm_name = "AdamW"
optm_lr = 1e-6
optm_impl = "fused"
optm_weight_decay = 0.01
optm_betas = [ 0.9, 0.999,]
optm_warmup_steps = 20
optm_grad_norm_clip = 1.0
async_tp_enabled = false
compile = false
param_dtype = "bfloat16"
fsdp_reduce_dtype = "float32"
fsdp_offload = false
fsdp_reshard_after_forward = "default"
train_batch_per_replica = 1
sync_weight_interval = 1
enable_validation = true
validation_freq = 100
validation_batch_per_replica = 2

[policy]
model_name_or_path = "./cosmos_reason1/policy/model/deepseek_vlm/tokenizer/deepseek_r1-pixtral-instruct"
model_max_length = 1024
model_gradient_checkpointing = true

[logging]
logger = ['console', 'wandb']
project_name = "cosmos_reason1"
experiment_name = "deepseek-vlm-sft"

[train.train_policy]
type = "sft"
dataset.name = "nvidia/Cosmos-Reason1-SFT-Dataset"
dataset.subset = "robovqa"
dataset.train_split = "understanding"
dataset.test_size = 100
enable_dataset_cache = false
dataloader_num_workers = 4
dataloader_prefetch_factor = 4
conversation_column_name = "conversations"

[train.ckpt]
enable_checkpoint = true
save_freq = 100
max_keep = 2
save_mode = "async"

[policy.parallelism]
n_init_replicas = 1
tp_size = 1
cp_size = 1
dp_shard_size = 8
pp_size = 1
dp_replicate_size = 1
cp_rotate_method = "allgather"
