redis = "12800"

[train]
resume = false
epoch = 1 
output_dir = "./outputs/cosmos-reason1-7b-p-fsdp1-tp2-r-tp2-pp1-grpo"
epsilon = 1e-6
optm_name = "AdamW"
optm_lr = 2e-6
optm_impl = "fused"
optm_weight_decay = 0.01
optm_betas = [ 0.9, 0.95,]
optm_warmup_steps = 20
optm_grad_norm_clip = 1.0
async_tp_enabled = false
compile = false
param_dtype = "bfloat16"
fsdp_reduce_dtype = "float32"
fsdp_offload = false
fsdp_reshard_after_forward = "default"
train_batch_per_replica = 8
sync_weight_interval = 1

[rollout]
gpu_memory_utilization = 0.7
enable_chunked_prefill = false
max_response_length = 6144
n_generation = 8
batch_size = 4
quantization = "none"


[rollout.sampling_config]
temperature = 0.6
top_p = 0.95
top_k = 50
repetition_penalty = 1.05

[policy]
model_name_or_path = "nvidia/Cosmos-Reason1-7B"
model_max_length = 10240
model_gradient_checkpointing = true

[logging]
logger = ['console', 'wandb']
project_name = "cosmos_rl_job"
experiment_name = "cosmos-reason1-rl"

[train.train_policy]
type = "grpo"
dataset.name = "nvidia/Cosmos-Reason1-RL-Dataset"
dataset.subset = "robovqa"
dataset.split = "rl"
enable_dataset_cache = false
dataloader_num_workers = 4
dataloader_prefetch_factor = 4
prompt_column_name = "qa_pairs"
reward_function = ["single_choice", "format"]
temperature = 0.9
epsilon_low = 0.2
epsilon_high = 0.2
kl_beta = 0.0
mu_iterations = 1
min_filter_prefix_tokens = 1
mini_batch = 1

[train.ckpt]
enable_checkpoint = true
save_freq = 100
max_keep = 2
save_mode = "async"


[rollout.parallelism]
n_init_replicas = 1
tp_size = 2
pp_size = 1

[policy.parallelism]
n_init_replicas = 1
tp_size = 2
cp_size = 1
dp_shard_size = 1
pp_size = 1
dp_replicate_size = 1
cp_rotate_method = "allgather"
