host="localhost"
port=8080
redis_host="localhost"
redis_port=6379

[[reward_args]]
reward_type = "cosmos_reason1"
# cosmos_reason1 reward can share the base cosmos_rl_reward environment so just the basic python is used as its venv_python
venv_python = "python"
model_path = "nvidia/Cosmos-Reason1-7B-Reward"
dtype = "float16"
enable = true

[[reward_args]]
reward_type = "dance_grpo"
venv_python = "/root/dance_grpo/bin/python"
model_path = "/workspace/VideoReward"
download_path = "/workspace"
dtype = "float16"
enable = true